# Generated by Django 2.1.5 on 2019-02-04 07:26

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='test.png', upload_to=products.models.get_path),
            preserve_default=False,
        ),
    ]
